package com.example.electrorui.usecase.model

import androidx.room.ColumnInfo
import com.example.electrorui.db.entityModel.RescateEntity


data class TipoRescate(
    var aeropuerto : Boolean,

    var carretero : Boolean,
    var tipoVehic : String,
    var lineaAutobus : String,
    var numeroEcono : String,
    var placas : String,
    var descripcion : String,
    var vehiculoAseg : Boolean,

    var casaSeguridad : Boolean,

    var centralAutobus : Boolean,

    var ferrocarril : Boolean,
    var empresa: String,

    var hotel : Boolean,
    var nombreHotel : String,

    var puestosADispo : Boolean,
    var juezCalif : Boolean,
    var reclusorio : Boolean,
    var policiaFede : Boolean,
    var dif : Boolean,
    var policiaEsta : Boolean,
    var policiaMuni : Boolean,
    var guardiaNaci : Boolean,
    var fiscalia : Boolean,
    var otrasAuto : Boolean,

    var voluntarios : Boolean,

    var otro : Boolean,

    var presuntosDelincuentes : Boolean,
    var numPresuntosDelincuentes : Int,
    var municipio : String,
    var puntoEstra : String,
) {

    //    --------- Vacio ----------
    constructor() : this(
        false,
        false,
        "",
        "",
        "",
        "",
        "",
        false,
        false,
        false,
        false,
        "",
        false,
        "",
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        0,
        "",
        ""
    )
//    
////    --------- Aeropuerto ----------
//    constructor(aeropuerto: Boolean, presuntosDelincuentes: Boolean, numPresuntosDelincuentes: Int) : this(
//        aeropuerto,
//        false,
//        "",
//        "",
//        "",
//        "",
//        "",
//        false,
//        false,
//        false,
//        false,
//        "",
//        false,
//        "",
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        presuntosDelincuentes,
//        numPresuntosDelincuentes,
//        ""
//    )
//
//    //    --------- Carretero ----------
//    constructor(carretero: Boolean,
//                tipoVehic: String,
//                lineaAutobus: String,
//                numeroEcono: String,
//                placas: String,
//                municipio: String,
//                vehiculoAseg: Boolean,
//                presuntosDelincuentes: Boolean,
//                numPresuntosDelincuentes: Int) : this(
//        false,
//        carretero,
//        tipoVehic,
//        lineaAutobus,
//        numeroEcono,
//        placas,
//        "",
//        vehiculoAseg,
//        false,
//        false,
//        false,
//        "",
//        false,
//        "",
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        presuntosDelincuentes,
//        numPresuntosDelincuentes,
//        municipio,
//    )
//
//    //    --------- Casa de seguridad ----------
//    constructor(casaSeguridad: Boolean, municipio: String ,presuntosDelincuentes: Boolean, numPresuntosDelincuentes: Int) : this(
//        false,
//        false,
//        "",
//        "",
//        "",
//        "",
//        "",
//        false,
//        casaSeguridad,
//        false,
//        false,
//        "",
//        false,
//        "",
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        presuntosDelincuentes,
//        numPresuntosDelincuentes,
//        municipio
//    )
//
//    //    --------- Central de Autobus ----------
//    constructor(presuntosDelincuentes: Boolean, numPresuntosDelincuentes: Int, centralAutobus: Boolean) : this(
//        false,
//        false,
//        "",
//        "",
//        "",
//        "",
//        "",
//        false,
//        false,
//        centralAutobus,
//        false,
//        "",
//        false,
//        "",
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        presuntosDelincuentes,
//        numPresuntosDelincuentes,
//        ""
//    )
//
//    constructor(ferrocarril: Boolean,presuntosDelincuentes: Boolean,empresa: String, numPresuntosDelincuentes: Int) : this(
//        false,
//        false,
//        "",
//        "",
//        "",
//        "",
//        "",
//        false,
//        false,
//        false,
//        ferrocarril,
//        empresa,
//        false,
//        "",
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        false,
//        presuntosDelincuentes,
//        numPresuntosDelincuentes,
//        ""
//    )

}